language: ruby
before_install: gem install bundler -v 1.11.2

rvm:
  - 1.9
  - 2.2.4
  - 2.3
  - 2.4

script: echo "Running tests against $(ruby -v) ..."

jobs:
  include:
    - stage: gem build
      rvm: 2.2
      script: echo "Deploying to rubygems.org ..."
      deploy:
        provider: rubygems
        #gem: omega2_gpio
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master